---
- name: Update repositories cache
  yum:
    update_cache: yes

- name: Install java 8 
  yum:
    name: java
    state: present

- name: Install vim
  yum:
    name: vim
    state: present

- name: Set the JAVA_HOME variable
  blockinfile:
    path: "{{ bash_file }}"
    marker: "# {mark} JAVA_HOME and JAVA_JRE environment variables"
    block: |
          export JAVA_HOME={{ java_home  }}
          export JRE_HOME={{ java_jre  }}
    state: present

- name: Add zeppelin user
  user:
    name: "{{ zeppelin_user }}"
    create_home: true
    home: "{{ zeppelin_user_home }}"

- name: Create {{ zeppelin_base_path }} directory
  file:
    path: "{{ zeppelin_base_path }}"
    state: directory
    owner: "{{ zeppelin_user  }}"
    group: "{{ zeppelin_user  }}"
    mode: 0766    

- name: Download Zepellin
  unarchive:
    src: "{{ zeppelin_package  }}"
    dest: "{{ zeppelin_base_path }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ zeppelin_user  }}"
    group: "{{ zeppelin_user  }}"

- name: Create {{ zeppelin_env_sh }} file
  file:
    path: "{{ zeppelin_env_sh }}"
    state: touch
    owner: "{{ zeppelin_user }}"
    group: "{{ zeppelin_user }}"

- name: Setup {{ zeppelin_env_sh }} file
  blockinfile:
    path: "{{ zeppelin_env_sh }}"
    marker: "# {mark} Zeppeling environment variables"
    block: |
          export MASTER=spark://master:7077
          export SPARK_HOME={{ spark_base_path }}
    state: present

- name: Create {{ zeppelin_service_file }} directory
  file:
    path: "{{ zeppelin_service_file }}"
    state: touch

- name: Populating the {{ zeppelin_service_file  }}
  blockinfile:
    path: "{{ zeppelin_service_file }}"
    marker: "# {mark} Zepellin service file"
    block: |
          [Unit]
          Description=Zeppelin service
          After=syslog.target network.target

          [Service]
          Type=forking
          ExecStart=/opt/zeppelin/bin/zeppelin-daemon.sh start
          ExecStop=/opt/zeppelin/bin/zeppelin-daemon.sh stop
          ExecReload=/opt/zeppelin/bin/zeppelin-daemon.sh reload
          User={{ zeppelin_user  }}
          Group={{ zeppelin_user  }}
          Restart=always

          [Install]
          WantedBy=multi-user.target
    state: present
  tags:
     - user

- name: Make sure zeppelin service is running
  systemd:
    state: reloaded
    daemon_reload: yes
    name: zeppelin
